name: Build & Deploy
on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          script:
            pm2 delete all
            cd pinkHawk/server
            git pull
            npm install
            npx prisma migrate
            pm2 start npm --start
