name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            echo 'Deployment Started'
            pm2 start npm -- start
            pm2 delete all
            cd pinkHawk/server
            echo 'Git Pull'
            git pull origin main
            npm install
            echo 'Apply migration'
            npx prisma migrate
            pm2 start npm -- start
            echo 'Deployment Done'
